debug: false
management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.fastcampus.board: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: johnny
    password: test!@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated #api로 노출 시킬지 여부를 정하는 전략 // default(기본값 - 퍼블릿 리포지토리),annotated(어노테이션 지정한 리포지토리만),all(전부),visibility(only 퍼블릭 리포지토리)

#---
#spring:
#  config:
#    activate:
#      on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none